version: '3'

services:
  web:
    restart: always
    build: .
    command: yarn dev
    ports:
      - 3000:3000
      - 9222:9222
    environment:
      - NODE_ENV=development
    volumes:
      - ./dist:/app/dist
