version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: beleza-na-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always
