version: '3.7'

services:
  belezanaweb-api:
    container_name: belezanaweb-api
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: 'mongodb://admin:admin@mongodb:27017/belezanaweb?authSource=admin'
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodata:/mongodata/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://admin:admin@mongodb:27017/'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongodb
    links:
      - mongodb
