### createProduct
POST http://localhost:3003/products/post
Content-Type: application/json

{
    "name": "L'Oréal Professionnel Expert Absolut Repair Cortex Lipidium - Máscara de Reconstrução 500g"
}

### editProductBySku
PUT http://localhost:3003/products/1
Content-Type: application/json

{
    "id": 2,
    "quantity": 12
}

### deleteProductBySku
DELETE http://localhost:3003/products/1

### getProductBySku
GET  http://localhost:3003/products/1